# Generated by Django 2.2.4 on 2022-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredChild',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('mobile_num', models.CharField(max_length=15)),
            ],
        ),
    ]
