# Generated by Django 2.2.4 on 2022-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_registeredchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredchild',
            name='image',
            field=models.ImageField(default=0, upload_to='registered_images/'),
            preserve_default=False,
        ),
    ]
